// <auto-generated />
using Inlog.Desafio.Backend.Infra.Database.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Inlog.Desafio.Backend.Infra.Database.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240422152829_createDatabase")]
    partial class createDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.29");

            modelBuilder.Entity("Inlog.Desafio.Backend.Domain.Models.Coordenadas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<float>("Longitude")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Coordenadas", (string)null);
                });

            modelBuilder.Entity("Inlog.Desafio.Backend.Domain.Models.Veiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Chassi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("CoordenadasId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cor")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("TEXT");

                    b.Property<int>("TipoVeiculo")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CoordenadasId");

                    b.ToTable("Veiculo", (string)null);
                });

            modelBuilder.Entity("Inlog.Desafio.Backend.Domain.Models.Veiculo", b =>
                {
                    b.HasOne("Inlog.Desafio.Backend.Domain.Models.Coordenadas", "Coordenadas")
                        .WithMany()
                        .HasForeignKey("CoordenadasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Coordenadas");
                });
#pragma warning restore 612, 618
        }
    }
}
